% Compute spectrogram

% Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
% Generated on: 01-Mar-2024 17:29:02

% Parameters
timeLimits = [0 25.48753]; % seconds
frequencyLimits = [0 2000]; % Hz
overlapPercent = 50;

%%
% Index into signal time region of interest
music_ROI = music(:);
sampleRate = 4000; % Hz
startTime = 0; % seconds
timeValues = startTime + (0:length(music_ROI)-1).'/sampleRate;
minIdx = timeValues >= timeLimits(1);
maxIdx = timeValues <= timeLimits(2);
music_ROI = music_ROI(minIdx&maxIdx);
timeValues = timeValues(minIdx&maxIdx);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[P,F,T] = pspectrum(music_ROI,timeValues, ...
    'spectrogram', ...
    'FrequencyLimits',frequencyLimits, ...
    'OverlapPercent',overlapPercent);
%%
imagesc(T(1:51),F,10*log10(P(:,1:51)))
set(gca,'YDir','Normal')
title('Spectrogram of Melody')
xlabel('Frequency (Hz)')
ylabel('Frequency (Hz)')
xlabel('Time (s)')
xlabel('Time(s)')
box off